/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZapticaImport } from './routes/zaptica'
import { Route as WhatsappgroupImport } from './routes/whatsappgroup'
import { Route as WelcomebyilyasImport } from './routes/welcomebyilyas'
import { Route as WebinarImport } from './routes/webinar'
import { Route as VallourImport } from './routes/vallour'
import { Route as TestImport } from './routes/test'
import { Route as TermsOfServiceImport } from './routes/terms-of-service'
import { Route as TechauditImport } from './routes/techaudit'
import { Route as SurgeCareImport } from './routes/surge-care'
import { Route as SuccessStoriesImport } from './routes/success-stories'
import { Route as StressfreeImport } from './routes/stressfree'
import { Route as PrivacyNoticeImport } from './routes/privacy-notice'
import { Route as PersonalityImport } from './routes/personality'
import { Route as NextwebinarImport } from './routes/nextwebinar'
import { Route as NewsletterImport } from './routes/newsletter'
import { Route as Mtf2025Import } from './routes/mtf2025'
import { Route as MastermindImport } from './routes/mastermind'
import { Route as LinktreeImport } from './routes/linktree'
import { Route as LinkedingroupImport } from './routes/linkedingroup'
import { Route as LinkedinZhagumImport } from './routes/linkedin-zhagum'
import { Route as LinkedinZayyanImport } from './routes/linkedin-zayyan'
import { Route as LinkedinIlyasImport } from './routes/linkedin-ilyas'
import { Route as KpibookImport } from './routes/kpibook'
import { Route as IqImport } from './routes/iq'
import { Route as HomeImport } from './routes/home'
import { Route as GptriageImport } from './routes/gptriage'
import { Route as FusionPodsImport } from './routes/fusion-pods'
import { Route as FeedbackImport } from './routes/feedback'
import { Route as FawriiImport } from './routes/fawrii'
import { Route as EnvCheckImport } from './routes/env-check'
import { Route as EnglishImport } from './routes/english'
import { Route as CspodsImport } from './routes/cspods'
import { Route as CsinfoImport } from './routes/csinfo'
import { Route as ContactImport } from './routes/contact'
import { Route as CloudSurgeWhitepaperImport } from './routes/cloud-surge-whitepaper'
import { Route as CharitystrategyImport } from './routes/charitystrategy'
import { Route as CareersImport } from './routes/careers'
import { Route as AboutImport } from './routes/about'
import { Route as GenaieraImport } from './routes/Genaiera'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZapticaRoute = ZapticaImport.update({
  id: '/zaptica',
  path: '/zaptica',
  getParentRoute: () => rootRoute,
} as any)

const WhatsappgroupRoute = WhatsappgroupImport.update({
  id: '/whatsappgroup',
  path: '/whatsappgroup',
  getParentRoute: () => rootRoute,
} as any)

const WelcomebyilyasRoute = WelcomebyilyasImport.update({
  id: '/welcomebyilyas',
  path: '/welcomebyilyas',
  getParentRoute: () => rootRoute,
} as any)

const WebinarRoute = WebinarImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => rootRoute,
} as any)

const VallourRoute = VallourImport.update({
  id: '/vallour',
  path: '/vallour',
  getParentRoute: () => rootRoute,
} as any)

const TestRoute = TestImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

const TermsOfServiceRoute = TermsOfServiceImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRoute,
} as any)

const TechauditRoute = TechauditImport.update({
  id: '/techaudit',
  path: '/techaudit',
  getParentRoute: () => rootRoute,
} as any)

const SurgeCareRoute = SurgeCareImport.update({
  id: '/surge-care',
  path: '/surge-care',
  getParentRoute: () => rootRoute,
} as any)

const SuccessStoriesRoute = SuccessStoriesImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRoute,
} as any)

const StressfreeRoute = StressfreeImport.update({
  id: '/stressfree',
  path: '/stressfree',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyNoticeRoute = PrivacyNoticeImport.update({
  id: '/privacy-notice',
  path: '/privacy-notice',
  getParentRoute: () => rootRoute,
} as any)

const PersonalityRoute = PersonalityImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => rootRoute,
} as any)

const NextwebinarRoute = NextwebinarImport.update({
  id: '/nextwebinar',
  path: '/nextwebinar',
  getParentRoute: () => rootRoute,
} as any)

const NewsletterRoute = NewsletterImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRoute,
} as any)

const Mtf2025Route = Mtf2025Import.update({
  id: '/mtf2025',
  path: '/mtf2025',
  getParentRoute: () => rootRoute,
} as any)

const MastermindRoute = MastermindImport.update({
  id: '/mastermind',
  path: '/mastermind',
  getParentRoute: () => rootRoute,
} as any)

const LinktreeRoute = LinktreeImport.update({
  id: '/linktree',
  path: '/linktree',
  getParentRoute: () => rootRoute,
} as any)

const LinkedingroupRoute = LinkedingroupImport.update({
  id: '/linkedingroup',
  path: '/linkedingroup',
  getParentRoute: () => rootRoute,
} as any)

const LinkedinZhagumRoute = LinkedinZhagumImport.update({
  id: '/linkedin-zhagum',
  path: '/linkedin-zhagum',
  getParentRoute: () => rootRoute,
} as any)

const LinkedinZayyanRoute = LinkedinZayyanImport.update({
  id: '/linkedin-zayyan',
  path: '/linkedin-zayyan',
  getParentRoute: () => rootRoute,
} as any)

const LinkedinIlyasRoute = LinkedinIlyasImport.update({
  id: '/linkedin-ilyas',
  path: '/linkedin-ilyas',
  getParentRoute: () => rootRoute,
} as any)

const KpibookRoute = KpibookImport.update({
  id: '/kpibook',
  path: '/kpibook',
  getParentRoute: () => rootRoute,
} as any)

const IqRoute = IqImport.update({
  id: '/iq',
  path: '/iq',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const GptriageRoute = GptriageImport.update({
  id: '/gptriage',
  path: '/gptriage',
  getParentRoute: () => rootRoute,
} as any)

const FusionPodsRoute = FusionPodsImport.update({
  id: '/fusion-pods',
  path: '/fusion-pods',
  getParentRoute: () => rootRoute,
} as any)

const FeedbackRoute = FeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const FawriiRoute = FawriiImport.update({
  id: '/fawrii',
  path: '/fawrii',
  getParentRoute: () => rootRoute,
} as any)

const EnvCheckRoute = EnvCheckImport.update({
  id: '/env-check',
  path: '/env-check',
  getParentRoute: () => rootRoute,
} as any)

const EnglishRoute = EnglishImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRoute,
} as any)

const CspodsRoute = CspodsImport.update({
  id: '/cspods',
  path: '/cspods',
  getParentRoute: () => rootRoute,
} as any)

const CsinfoRoute = CsinfoImport.update({
  id: '/csinfo',
  path: '/csinfo',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const CloudSurgeWhitepaperRoute = CloudSurgeWhitepaperImport.update({
  id: '/cloud-surge-whitepaper',
  path: '/cloud-surge-whitepaper',
  getParentRoute: () => rootRoute,
} as any)

const CharitystrategyRoute = CharitystrategyImport.update({
  id: '/charitystrategy',
  path: '/charitystrategy',
  getParentRoute: () => rootRoute,
} as any)

const CareersRoute = CareersImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const GenaieraRoute = GenaieraImport.update({
  id: '/Genaiera',
  path: '/Genaiera',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Genaiera': {
      id: '/Genaiera'
      path: '/Genaiera'
      fullPath: '/Genaiera'
      preLoaderRoute: typeof GenaieraImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersImport
      parentRoute: typeof rootRoute
    }
    '/charitystrategy': {
      id: '/charitystrategy'
      path: '/charitystrategy'
      fullPath: '/charitystrategy'
      preLoaderRoute: typeof CharitystrategyImport
      parentRoute: typeof rootRoute
    }
    '/cloud-surge-whitepaper': {
      id: '/cloud-surge-whitepaper'
      path: '/cloud-surge-whitepaper'
      fullPath: '/cloud-surge-whitepaper'
      preLoaderRoute: typeof CloudSurgeWhitepaperImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/csinfo': {
      id: '/csinfo'
      path: '/csinfo'
      fullPath: '/csinfo'
      preLoaderRoute: typeof CsinfoImport
      parentRoute: typeof rootRoute
    }
    '/cspods': {
      id: '/cspods'
      path: '/cspods'
      fullPath: '/cspods'
      preLoaderRoute: typeof CspodsImport
      parentRoute: typeof rootRoute
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishImport
      parentRoute: typeof rootRoute
    }
    '/env-check': {
      id: '/env-check'
      path: '/env-check'
      fullPath: '/env-check'
      preLoaderRoute: typeof EnvCheckImport
      parentRoute: typeof rootRoute
    }
    '/fawrii': {
      id: '/fawrii'
      path: '/fawrii'
      fullPath: '/fawrii'
      preLoaderRoute: typeof FawriiImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/fusion-pods': {
      id: '/fusion-pods'
      path: '/fusion-pods'
      fullPath: '/fusion-pods'
      preLoaderRoute: typeof FusionPodsImport
      parentRoute: typeof rootRoute
    }
    '/gptriage': {
      id: '/gptriage'
      path: '/gptriage'
      fullPath: '/gptriage'
      preLoaderRoute: typeof GptriageImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/iq': {
      id: '/iq'
      path: '/iq'
      fullPath: '/iq'
      preLoaderRoute: typeof IqImport
      parentRoute: typeof rootRoute
    }
    '/kpibook': {
      id: '/kpibook'
      path: '/kpibook'
      fullPath: '/kpibook'
      preLoaderRoute: typeof KpibookImport
      parentRoute: typeof rootRoute
    }
    '/linkedin-ilyas': {
      id: '/linkedin-ilyas'
      path: '/linkedin-ilyas'
      fullPath: '/linkedin-ilyas'
      preLoaderRoute: typeof LinkedinIlyasImport
      parentRoute: typeof rootRoute
    }
    '/linkedin-zayyan': {
      id: '/linkedin-zayyan'
      path: '/linkedin-zayyan'
      fullPath: '/linkedin-zayyan'
      preLoaderRoute: typeof LinkedinZayyanImport
      parentRoute: typeof rootRoute
    }
    '/linkedin-zhagum': {
      id: '/linkedin-zhagum'
      path: '/linkedin-zhagum'
      fullPath: '/linkedin-zhagum'
      preLoaderRoute: typeof LinkedinZhagumImport
      parentRoute: typeof rootRoute
    }
    '/linkedingroup': {
      id: '/linkedingroup'
      path: '/linkedingroup'
      fullPath: '/linkedingroup'
      preLoaderRoute: typeof LinkedingroupImport
      parentRoute: typeof rootRoute
    }
    '/linktree': {
      id: '/linktree'
      path: '/linktree'
      fullPath: '/linktree'
      preLoaderRoute: typeof LinktreeImport
      parentRoute: typeof rootRoute
    }
    '/mastermind': {
      id: '/mastermind'
      path: '/mastermind'
      fullPath: '/mastermind'
      preLoaderRoute: typeof MastermindImport
      parentRoute: typeof rootRoute
    }
    '/mtf2025': {
      id: '/mtf2025'
      path: '/mtf2025'
      fullPath: '/mtf2025'
      preLoaderRoute: typeof Mtf2025Import
      parentRoute: typeof rootRoute
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterImport
      parentRoute: typeof rootRoute
    }
    '/nextwebinar': {
      id: '/nextwebinar'
      path: '/nextwebinar'
      fullPath: '/nextwebinar'
      preLoaderRoute: typeof NextwebinarImport
      parentRoute: typeof rootRoute
    }
    '/personality': {
      id: '/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof PersonalityImport
      parentRoute: typeof rootRoute
    }
    '/privacy-notice': {
      id: '/privacy-notice'
      path: '/privacy-notice'
      fullPath: '/privacy-notice'
      preLoaderRoute: typeof PrivacyNoticeImport
      parentRoute: typeof rootRoute
    }
    '/stressfree': {
      id: '/stressfree'
      path: '/stressfree'
      fullPath: '/stressfree'
      preLoaderRoute: typeof StressfreeImport
      parentRoute: typeof rootRoute
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesImport
      parentRoute: typeof rootRoute
    }
    '/surge-care': {
      id: '/surge-care'
      path: '/surge-care'
      fullPath: '/surge-care'
      preLoaderRoute: typeof SurgeCareImport
      parentRoute: typeof rootRoute
    }
    '/techaudit': {
      id: '/techaudit'
      path: '/techaudit'
      fullPath: '/techaudit'
      preLoaderRoute: typeof TechauditImport
      parentRoute: typeof rootRoute
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestImport
      parentRoute: typeof rootRoute
    }
    '/vallour': {
      id: '/vallour'
      path: '/vallour'
      fullPath: '/vallour'
      preLoaderRoute: typeof VallourImport
      parentRoute: typeof rootRoute
    }
    '/webinar': {
      id: '/webinar'
      path: '/webinar'
      fullPath: '/webinar'
      preLoaderRoute: typeof WebinarImport
      parentRoute: typeof rootRoute
    }
    '/welcomebyilyas': {
      id: '/welcomebyilyas'
      path: '/welcomebyilyas'
      fullPath: '/welcomebyilyas'
      preLoaderRoute: typeof WelcomebyilyasImport
      parentRoute: typeof rootRoute
    }
    '/whatsappgroup': {
      id: '/whatsappgroup'
      path: '/whatsappgroup'
      fullPath: '/whatsappgroup'
      preLoaderRoute: typeof WhatsappgroupImport
      parentRoute: typeof rootRoute
    }
    '/zaptica': {
      id: '/zaptica'
      path: '/zaptica'
      fullPath: '/zaptica'
      preLoaderRoute: typeof ZapticaImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Genaiera': typeof GenaieraRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/charitystrategy': typeof CharitystrategyRoute
  '/cloud-surge-whitepaper': typeof CloudSurgeWhitepaperRoute
  '/contact': typeof ContactRoute
  '/csinfo': typeof CsinfoRoute
  '/cspods': typeof CspodsRoute
  '/english': typeof EnglishRoute
  '/env-check': typeof EnvCheckRoute
  '/fawrii': typeof FawriiRoute
  '/feedback': typeof FeedbackRoute
  '/fusion-pods': typeof FusionPodsRoute
  '/gptriage': typeof GptriageRoute
  '/home': typeof HomeRoute
  '/iq': typeof IqRoute
  '/kpibook': typeof KpibookRoute
  '/linkedin-ilyas': typeof LinkedinIlyasRoute
  '/linkedin-zayyan': typeof LinkedinZayyanRoute
  '/linkedin-zhagum': typeof LinkedinZhagumRoute
  '/linkedingroup': typeof LinkedingroupRoute
  '/linktree': typeof LinktreeRoute
  '/mastermind': typeof MastermindRoute
  '/mtf2025': typeof Mtf2025Route
  '/newsletter': typeof NewsletterRoute
  '/nextwebinar': typeof NextwebinarRoute
  '/personality': typeof PersonalityRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/stressfree': typeof StressfreeRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/surge-care': typeof SurgeCareRoute
  '/techaudit': typeof TechauditRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/vallour': typeof VallourRoute
  '/webinar': typeof WebinarRoute
  '/welcomebyilyas': typeof WelcomebyilyasRoute
  '/whatsappgroup': typeof WhatsappgroupRoute
  '/zaptica': typeof ZapticaRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Genaiera': typeof GenaieraRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/charitystrategy': typeof CharitystrategyRoute
  '/cloud-surge-whitepaper': typeof CloudSurgeWhitepaperRoute
  '/contact': typeof ContactRoute
  '/csinfo': typeof CsinfoRoute
  '/cspods': typeof CspodsRoute
  '/english': typeof EnglishRoute
  '/env-check': typeof EnvCheckRoute
  '/fawrii': typeof FawriiRoute
  '/feedback': typeof FeedbackRoute
  '/fusion-pods': typeof FusionPodsRoute
  '/gptriage': typeof GptriageRoute
  '/home': typeof HomeRoute
  '/iq': typeof IqRoute
  '/kpibook': typeof KpibookRoute
  '/linkedin-ilyas': typeof LinkedinIlyasRoute
  '/linkedin-zayyan': typeof LinkedinZayyanRoute
  '/linkedin-zhagum': typeof LinkedinZhagumRoute
  '/linkedingroup': typeof LinkedingroupRoute
  '/linktree': typeof LinktreeRoute
  '/mastermind': typeof MastermindRoute
  '/mtf2025': typeof Mtf2025Route
  '/newsletter': typeof NewsletterRoute
  '/nextwebinar': typeof NextwebinarRoute
  '/personality': typeof PersonalityRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/stressfree': typeof StressfreeRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/surge-care': typeof SurgeCareRoute
  '/techaudit': typeof TechauditRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/vallour': typeof VallourRoute
  '/webinar': typeof WebinarRoute
  '/welcomebyilyas': typeof WelcomebyilyasRoute
  '/whatsappgroup': typeof WhatsappgroupRoute
  '/zaptica': typeof ZapticaRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Genaiera': typeof GenaieraRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/charitystrategy': typeof CharitystrategyRoute
  '/cloud-surge-whitepaper': typeof CloudSurgeWhitepaperRoute
  '/contact': typeof ContactRoute
  '/csinfo': typeof CsinfoRoute
  '/cspods': typeof CspodsRoute
  '/english': typeof EnglishRoute
  '/env-check': typeof EnvCheckRoute
  '/fawrii': typeof FawriiRoute
  '/feedback': typeof FeedbackRoute
  '/fusion-pods': typeof FusionPodsRoute
  '/gptriage': typeof GptriageRoute
  '/home': typeof HomeRoute
  '/iq': typeof IqRoute
  '/kpibook': typeof KpibookRoute
  '/linkedin-ilyas': typeof LinkedinIlyasRoute
  '/linkedin-zayyan': typeof LinkedinZayyanRoute
  '/linkedin-zhagum': typeof LinkedinZhagumRoute
  '/linkedingroup': typeof LinkedingroupRoute
  '/linktree': typeof LinktreeRoute
  '/mastermind': typeof MastermindRoute
  '/mtf2025': typeof Mtf2025Route
  '/newsletter': typeof NewsletterRoute
  '/nextwebinar': typeof NextwebinarRoute
  '/personality': typeof PersonalityRoute
  '/privacy-notice': typeof PrivacyNoticeRoute
  '/stressfree': typeof StressfreeRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/surge-care': typeof SurgeCareRoute
  '/techaudit': typeof TechauditRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/test': typeof TestRoute
  '/vallour': typeof VallourRoute
  '/webinar': typeof WebinarRoute
  '/welcomebyilyas': typeof WelcomebyilyasRoute
  '/whatsappgroup': typeof WhatsappgroupRoute
  '/zaptica': typeof ZapticaRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Genaiera'
    | '/about'
    | '/careers'
    | '/charitystrategy'
    | '/cloud-surge-whitepaper'
    | '/contact'
    | '/csinfo'
    | '/cspods'
    | '/english'
    | '/env-check'
    | '/fawrii'
    | '/feedback'
    | '/fusion-pods'
    | '/gptriage'
    | '/home'
    | '/iq'
    | '/kpibook'
    | '/linkedin-ilyas'
    | '/linkedin-zayyan'
    | '/linkedin-zhagum'
    | '/linkedingroup'
    | '/linktree'
    | '/mastermind'
    | '/mtf2025'
    | '/newsletter'
    | '/nextwebinar'
    | '/personality'
    | '/privacy-notice'
    | '/stressfree'
    | '/success-stories'
    | '/surge-care'
    | '/techaudit'
    | '/terms-of-service'
    | '/test'
    | '/vallour'
    | '/webinar'
    | '/welcomebyilyas'
    | '/whatsappgroup'
    | '/zaptica'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Genaiera'
    | '/about'
    | '/careers'
    | '/charitystrategy'
    | '/cloud-surge-whitepaper'
    | '/contact'
    | '/csinfo'
    | '/cspods'
    | '/english'
    | '/env-check'
    | '/fawrii'
    | '/feedback'
    | '/fusion-pods'
    | '/gptriage'
    | '/home'
    | '/iq'
    | '/kpibook'
    | '/linkedin-ilyas'
    | '/linkedin-zayyan'
    | '/linkedin-zhagum'
    | '/linkedingroup'
    | '/linktree'
    | '/mastermind'
    | '/mtf2025'
    | '/newsletter'
    | '/nextwebinar'
    | '/personality'
    | '/privacy-notice'
    | '/stressfree'
    | '/success-stories'
    | '/surge-care'
    | '/techaudit'
    | '/terms-of-service'
    | '/test'
    | '/vallour'
    | '/webinar'
    | '/welcomebyilyas'
    | '/whatsappgroup'
    | '/zaptica'
  id:
    | '__root__'
    | '/'
    | '/Genaiera'
    | '/about'
    | '/careers'
    | '/charitystrategy'
    | '/cloud-surge-whitepaper'
    | '/contact'
    | '/csinfo'
    | '/cspods'
    | '/english'
    | '/env-check'
    | '/fawrii'
    | '/feedback'
    | '/fusion-pods'
    | '/gptriage'
    | '/home'
    | '/iq'
    | '/kpibook'
    | '/linkedin-ilyas'
    | '/linkedin-zayyan'
    | '/linkedin-zhagum'
    | '/linkedingroup'
    | '/linktree'
    | '/mastermind'
    | '/mtf2025'
    | '/newsletter'
    | '/nextwebinar'
    | '/personality'
    | '/privacy-notice'
    | '/stressfree'
    | '/success-stories'
    | '/surge-care'
    | '/techaudit'
    | '/terms-of-service'
    | '/test'
    | '/vallour'
    | '/webinar'
    | '/welcomebyilyas'
    | '/whatsappgroup'
    | '/zaptica'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenaieraRoute: typeof GenaieraRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CharitystrategyRoute: typeof CharitystrategyRoute
  CloudSurgeWhitepaperRoute: typeof CloudSurgeWhitepaperRoute
  ContactRoute: typeof ContactRoute
  CsinfoRoute: typeof CsinfoRoute
  CspodsRoute: typeof CspodsRoute
  EnglishRoute: typeof EnglishRoute
  EnvCheckRoute: typeof EnvCheckRoute
  FawriiRoute: typeof FawriiRoute
  FeedbackRoute: typeof FeedbackRoute
  FusionPodsRoute: typeof FusionPodsRoute
  GptriageRoute: typeof GptriageRoute
  HomeRoute: typeof HomeRoute
  IqRoute: typeof IqRoute
  KpibookRoute: typeof KpibookRoute
  LinkedinIlyasRoute: typeof LinkedinIlyasRoute
  LinkedinZayyanRoute: typeof LinkedinZayyanRoute
  LinkedinZhagumRoute: typeof LinkedinZhagumRoute
  LinkedingroupRoute: typeof LinkedingroupRoute
  LinktreeRoute: typeof LinktreeRoute
  MastermindRoute: typeof MastermindRoute
  Mtf2025Route: typeof Mtf2025Route
  NewsletterRoute: typeof NewsletterRoute
  NextwebinarRoute: typeof NextwebinarRoute
  PersonalityRoute: typeof PersonalityRoute
  PrivacyNoticeRoute: typeof PrivacyNoticeRoute
  StressfreeRoute: typeof StressfreeRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SurgeCareRoute: typeof SurgeCareRoute
  TechauditRoute: typeof TechauditRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  TestRoute: typeof TestRoute
  VallourRoute: typeof VallourRoute
  WebinarRoute: typeof WebinarRoute
  WelcomebyilyasRoute: typeof WelcomebyilyasRoute
  WhatsappgroupRoute: typeof WhatsappgroupRoute
  ZapticaRoute: typeof ZapticaRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenaieraRoute: GenaieraRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CharitystrategyRoute: CharitystrategyRoute,
  CloudSurgeWhitepaperRoute: CloudSurgeWhitepaperRoute,
  ContactRoute: ContactRoute,
  CsinfoRoute: CsinfoRoute,
  CspodsRoute: CspodsRoute,
  EnglishRoute: EnglishRoute,
  EnvCheckRoute: EnvCheckRoute,
  FawriiRoute: FawriiRoute,
  FeedbackRoute: FeedbackRoute,
  FusionPodsRoute: FusionPodsRoute,
  GptriageRoute: GptriageRoute,
  HomeRoute: HomeRoute,
  IqRoute: IqRoute,
  KpibookRoute: KpibookRoute,
  LinkedinIlyasRoute: LinkedinIlyasRoute,
  LinkedinZayyanRoute: LinkedinZayyanRoute,
  LinkedinZhagumRoute: LinkedinZhagumRoute,
  LinkedingroupRoute: LinkedingroupRoute,
  LinktreeRoute: LinktreeRoute,
  MastermindRoute: MastermindRoute,
  Mtf2025Route: Mtf2025Route,
  NewsletterRoute: NewsletterRoute,
  NextwebinarRoute: NextwebinarRoute,
  PersonalityRoute: PersonalityRoute,
  PrivacyNoticeRoute: PrivacyNoticeRoute,
  StressfreeRoute: StressfreeRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SurgeCareRoute: SurgeCareRoute,
  TechauditRoute: TechauditRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  TestRoute: TestRoute,
  VallourRoute: VallourRoute,
  WebinarRoute: WebinarRoute,
  WelcomebyilyasRoute: WelcomebyilyasRoute,
  WhatsappgroupRoute: WhatsappgroupRoute,
  ZapticaRoute: ZapticaRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Genaiera",
        "/about",
        "/careers",
        "/charitystrategy",
        "/cloud-surge-whitepaper",
        "/contact",
        "/csinfo",
        "/cspods",
        "/english",
        "/env-check",
        "/fawrii",
        "/feedback",
        "/fusion-pods",
        "/gptriage",
        "/home",
        "/iq",
        "/kpibook",
        "/linkedin-ilyas",
        "/linkedin-zayyan",
        "/linkedin-zhagum",
        "/linkedingroup",
        "/linktree",
        "/mastermind",
        "/mtf2025",
        "/newsletter",
        "/nextwebinar",
        "/personality",
        "/privacy-notice",
        "/stressfree",
        "/success-stories",
        "/surge-care",
        "/techaudit",
        "/terms-of-service",
        "/test",
        "/vallour",
        "/webinar",
        "/welcomebyilyas",
        "/whatsappgroup",
        "/zaptica"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Genaiera": {
      "filePath": "Genaiera.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/careers": {
      "filePath": "careers.tsx"
    },
    "/charitystrategy": {
      "filePath": "charitystrategy.tsx"
    },
    "/cloud-surge-whitepaper": {
      "filePath": "cloud-surge-whitepaper.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/csinfo": {
      "filePath": "csinfo.tsx"
    },
    "/cspods": {
      "filePath": "cspods.tsx"
    },
    "/english": {
      "filePath": "english.tsx"
    },
    "/env-check": {
      "filePath": "env-check.tsx"
    },
    "/fawrii": {
      "filePath": "fawrii.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/fusion-pods": {
      "filePath": "fusion-pods.tsx"
    },
    "/gptriage": {
      "filePath": "gptriage.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/iq": {
      "filePath": "iq.tsx"
    },
    "/kpibook": {
      "filePath": "kpibook.tsx"
    },
    "/linkedin-ilyas": {
      "filePath": "linkedin-ilyas.tsx"
    },
    "/linkedin-zayyan": {
      "filePath": "linkedin-zayyan.tsx"
    },
    "/linkedin-zhagum": {
      "filePath": "linkedin-zhagum.tsx"
    },
    "/linkedingroup": {
      "filePath": "linkedingroup.tsx"
    },
    "/linktree": {
      "filePath": "linktree.tsx"
    },
    "/mastermind": {
      "filePath": "mastermind.tsx"
    },
    "/mtf2025": {
      "filePath": "mtf2025.tsx"
    },
    "/newsletter": {
      "filePath": "newsletter.tsx"
    },
    "/nextwebinar": {
      "filePath": "nextwebinar.tsx"
    },
    "/personality": {
      "filePath": "personality.tsx"
    },
    "/privacy-notice": {
      "filePath": "privacy-notice.tsx"
    },
    "/stressfree": {
      "filePath": "stressfree.tsx"
    },
    "/success-stories": {
      "filePath": "success-stories.tsx"
    },
    "/surge-care": {
      "filePath": "surge-care.tsx"
    },
    "/techaudit": {
      "filePath": "techaudit.tsx"
    },
    "/terms-of-service": {
      "filePath": "terms-of-service.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    },
    "/vallour": {
      "filePath": "vallour.tsx"
    },
    "/webinar": {
      "filePath": "webinar.tsx"
    },
    "/welcomebyilyas": {
      "filePath": "welcomebyilyas.tsx"
    },
    "/whatsappgroup": {
      "filePath": "whatsappgroup.tsx"
    },
    "/zaptica": {
      "filePath": "zaptica.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
